"""update tables

Revision ID: 552ffb990176
Revises: 
Create Date: 2025-11-13 18:32:00.557190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '552ffb990176'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('answer_type', sa.Enum('open', 'close', 'multiple', name='answer_type'), nullable=False),
    sa.Column('survey_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('choice',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    role_enum = postgresql.ENUM('user', 'superuser', name='role')
    role_enum.create(op.get_bind(), checkfirst=True)

    op.execute('ALTER TABLE "user" ALTER COLUMN role TYPE role USING role::role')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = postgresql.ENUM('user', 'superuser', name='role')
    role_enum.create(op.get_bind(), checkfirst=True)

    op.execute('ALTER TABLE "user" ALTER COLUMN role TYPE role USING role::role')
    op.drop_table('choice')
    op.drop_table('question')
    # ### end Alembic commands ###
