"""add confirm_mail column to user

Revision ID: d00767232128
Revises: 
Create Date: 2026-01-02 17:31:19.938661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd00767232128'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "email_confirmed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        )
    )

    # (opcjonalnie) usuń default po uzupełnieniu danych
    op.alter_column(
        "user",
        "email_confirmed",
        server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_confirmed')
